### ISSUE TITLE
Criar as tabelas do banco de dados

### ISSUE THREAD

**Issue by thevitorhideki** [insper-tecnologias-web/projeto-3-equipe-legal-2#2]
# Como criar as tabelas no Next?
O Next possui a grande vantagem de nós podermos executar código do lado do servidor, e não epenas do cliente como em Vite. Portanto é possível criar um backend completo no mesmo projeto que o frontend, análogo como vimos em Django.

Vamos partir do princípio que você não sabe nada de node e nem tem ideia de como criar uma tabela. Para isso utilizamos um ORM (Object-Relational mapping) para facilitar a escrita de queries. Existem várias tecnologias para isso, mas a que eu tenho mais familiaridade é o [Prisma](https://www.prisma.io/).

Mas antes de qualquer coisa, vamos criar o nosso container (ou não, você pode usar apenas o sqlite) para construir as tabelas e aplicar migrations. 

## Banco de dados

Caso você opte para usar apenas o sqlite, tenha em mente que isso não vai durar muito tempo, recomendo já criar o container.

Então vamos lá, para criar o container vamos utilizar o docker compose file (se você quiser saber mais, ChatGPT). Como estou com preguiça e já escrevi demais, vou colocar um pronto aqui. Crie um arquivo na raiz do projeto com o nome `docker-compose.yml` e coloque o conteúdo a seguir:

```yml
services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: S3cret123
      POSTGRESQL_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
```

Com isso feito, execute no terminal:
```shell
docker compose up -d
```

Maravilha, próximo passo!

## Prisma

Beleza, agora com o banco de dados rodando conseguimos criar as tabelas. Pode parecer um pouco complicado no começo, então se precisar de ajuda busque a documentação, ChatGPT e em ultimo caso, eu. Aqui está um link de um tutorial de como [começar](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases-typescript-postgresql), não vá muito longe, você pode se perder!

Ah, e instale a extensão do Prisma 👯‍♂️ 

## Tabelas

![image](https://github.com/user-attachments/assets/12aa6aa3-7d68-4a4c-acae-badc25a2b55b)

Se você seguir o tutorial que eu coloquei acima você vai conseguir fazer essas tabelas de boa. Caso tenham dúvida, me chamem :P
